@baseUrl = http://localhost:3000

@urlPath = api 

###

POST {{baseUrl}}/{{urlPath}}/orders
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "fullName": "Eldad Mamo",
  "email": "eldadfikre456@gmail.com",
  "state": "ethiopia",
  "city": "addis ababa",
  "locality": "ET",
  "productName": "Gucci Oversize",
  "productPrice": 400,
  "quantity": 4,
  "category": "Fashion",
  "image": "https://res.cloudinary.com/dggixttgq/image/upload/v1742852841/rpbikog50ky0omzbs0cw",
  "buyerId": "ff",
  "vendorId": "fff"
}

###
GET {{baseUrl}}/{{urlPath}}/orders/67e6dea3eb2611a2eba5944a
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/orders/vendors/67ed4744d0980f67457547b4
Content-Type: application/json
Accept: application/json
withCredentials: true


###
PATCH {{baseUrl}}/{{urlPath}}/orders/67f01279151d580ba37c4b75/delivered
Content-Type: application/json
Accept: application/json
withCredentials: true


###
DELETE {{baseUrl}}/{{urlPath}}/orders/67f0128c151d580ba37c4b77
Content-Type: application/json
Accept: application/json
withCredentials: true







