@baseUrl = http://localhost:3000

@urlPath = api

###

POST {{baseUrl}}/{{urlPath}}/add-product
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "productName":"Samsung A10", 
  "productPrice": 1000, 
  "quantity":15, 
  "description":"This is the best part of the show", 
  "category": "computer", 
  "subCategory":"shirt",
  "vendorId": "123456",
  "fullName": "Eldad",
  "images": ["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.carguide.ph%2Fsearch%3Fupdated-max%3D2023-10-25T17%3A01%3A00-07%3A00%26max-results%3D28%26m%3D0&psig=AOvVaw1DuPAdHValb-5x3R8apXFt&ust=1743286997096000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIj-kaLorYwDFQAAAAAdAAAAABAJ"]
}

###


GET {{baseUrl}}/{{urlPath}}/popular-products
Content-Type: application/json
Accept: application/json
withCredentials: true


###

GET {{baseUrl}}/{{urlPath}}/recommended-products
Content-Type: application/json
Accept: application/json
withCredentials: true


###

GET {{baseUrl}}/{{urlPath}}/products-by-category/baby
Content-Type: application/json
Accept: application/json
withCredentials: true



###

GET {{baseUrl}}/{{urlPath}}/top-rated-products
Content-Type: application/json
Accept: application/json
withCredentials: true

###

GET {{baseUrl}}/{{urlPath}}/products-by-subcategories/accessories
Content-Type: application/json
Accept: application/json
withCredentials: true


###


GET {{baseUrl}}/{{urlPath}}/products/vendor/67fd8d9a4237f0ce9ec2966c
Content-Type: application/json
Accept: application/json
withCredentials: true

###


PUT {{baseUrl}}/{{urlPath}}/edit-product/67fd8fe04237f0ce9ec296bb
Content-Type: application/json
Accept: application/json
withCredentials: true
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmQ4ZDlhNDIzN2YwY2U5ZWMyOTY2YyIsImlhdCI6MTc0NDkyMzcwMSwiZXhwIjoxNzQ0OTI2NzAxfQ.HC-RbRhAWrEXI47dCkSqoPgO-MDO8bgjZBJqURdnGTg

{
  "productName":"stylish cool dress", 
  "productPrice": 400, 
  "quantity":20, 
  "description":"this is the finest cloths in paris best cloth", 
  "category": "dress", 
  "subCategory":"stylish dress",
  "vendorId": "67fd8d9a4237f0ce9ec2966c",
  "fullName": "abenezer",
  "images": ["https://res.cloudinary.com/dggixttgq/image/upload/v1744670689/stylish%20cool%20dress/pzs9zgb01k8u7e8umdlq.jpg"]
}



