@baseUrl = http://localhost:3000

@urlPath = api

###

POST {{baseUrl}}/{{urlPath}}/product-review
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "buyerId": "67e6dea3eb2611a2eba5944a", 
  "email": "eldadfikre456@gmail.com", 
  "fullName": "Eldad Fikre Mamo", 
  "productId": "67ee80d2b5e8f3f1a7d1800b", 
  "rating": 4.5, 
  "review": "Great Product!"
}

###

GET {{baseUrl}}/{{urlPath}}/reviews
Content-Type: application/json
Accept: application/json
withCredentials: true

