@baseUrl = http://localhost:3000

@urlPath = api

###

POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "fullName":"eldad",
  "email": "eldadf456@gmail.com" ,
  "password":"12345678"
}


###

POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "eldadfikre456@gmail.com" ,
  "password":"123456"
}

###


POST {{baseUrl}}/{{urlPath}}/verify-otp
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "eldadf456@gmail.com",
  "otp": "982331"
}

###

PUT {{baseUrl}}/{{urlPath}}/users/67e6dea3eb2611a2eba5944a
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "state": "Ethiopia",
  "city": "Addis Ababa",
  "locality":"ET"
}



###

GET {{baseUrl}}/{{urlPath}}/users
Content-Type: application/json
Accept: application/json
withCredentials: true


###

POST {{baseUrl}}/tokenIsValid
Content-Type: application/json
Accept: application/json
withCredentials: true
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmVmNTM5M2FmZjg3YzAzNDAwYmVhZSIsImlhdCI6MTc0NDgwNDY5NCwiZXhwIjoxNzQ0ODA0NzU0fQ.280YudcYV9iGVS8g8Rem4zK2coxH19alvjZbpmYnVZM

