@baseUrl = http://localhost:3000

@urlPath = api

###

POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "fullName":"eldad",
  "email": "eldadfikre456@gmail.com" ,
  "password":"12345678"
}


###

POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "eldadf456@gmail.com" ,
  "password":"12345678"
}


###

PUT {{baseUrl}}/{{urlPath}}/users/67e6dea3eb2611a2eba5944a
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "state": "Ethiopia",
  "city": "Addis Ababa",
  "locality":"ET"
}



###

GET {{baseUrl}}/{{urlPath}}/users
Content-Type: application/json
Accept: application/json
withCredentials: true

